import Link from 'next/link';

export default function DocsTokenAxnPage() {
  return (
    <div>
      <nav className="mb-8">
        <ol className="flex items-center space-x-2 text-sm text-gray-400">
          <li><Link href="/" className="hover:text-white transition-colors">Statera</Link></li>
          <li className="text-gray-600">/</li>
          <li><Link href="/docs" className="hover:text-white transition-colors">Docs</Link></li>
          <li className="text-gray-600">/</li>
          <li className="text-white">The STA token</li>
        </ol>
      </nav>

      <div className="mb-8">
        <h1 className="text-4xl font-bold text-white mb-4">The STA token: capture the value of the Statera protocol</h1>
        <p className="text-xl text-[#5a9a9a] leading-relaxed">
          At Statera, our token is not just a utility token—it is deeply integrated into the ecosystem and our strategies.
        </p>
      </div>

      <div className="prose prose-invert max-w-none">
        <section className="space-y-6">
          <p className="text-[#5a9a9a] leading-relaxed">
            At Statera, our token is <strong>not just a utility token</strong>—it is <strong>deeply integrated into the ecosystem and our strategies</strong>. From day one, we designed its allocation, utility, and economic role to <strong>create and redistribute value</strong> to those who believe in our vision.
          </p>
          <p className="text-[#5a9a9a] leading-relaxed">
            The STA token is built to capture the growth generated by the strategies and platform activity
          </p>
          <p className="text-[#5a9a9a] leading-relaxed font-semibold">
            <strong>Holding STA means owning a stake in the future we&apos;re building</strong>—a simpler, more efficient, and universally accessible Web3.
          </p>
        </section>
      </div>
    </div>
  );
}
